# Remote action to execute e2e functional tests

name: E2E Functional Tests

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  functional-test:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2.4.0
      with:
        ref: feature-iam
    
    # Runs a single command using the runners shell
    - name: Execute functional tests
      run: make functional-test
